pub_rate: 1.0 # Optional
#base_path: '' # Optional, prepended to all diagnostic output
analyzers:
  computers:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Computers
    analyzers:
      b1:
        type: diagnostic_aggregator/DiscardAnalyzer
        path: b1
        contains: 'b1'

  sensors:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Sensors
    analyzers:
      laser_top:
        type: diagnostic_aggregator/DiscardAnalyzer
        path: Scan Front
        contains: 'laser_front'
      laser_rear:
        type: diagnostic_aggregator/DiscardAnalyzer
        path: Scan Rear
        contains: 'laser_rear'
      laser_front:
        type: diagnostic_aggregator/DiscardAnalyzer
        path: Scan Left
        contains: 'laser_left'

  io:
    type: diagnostic_aggregator/AnalyzerGroup
    path: IO
    analyzers:
      joystick:
        type: diagnostic_aggregator/DiscardAnalyzer
        path: Joystick
        contains: 'joy'

  motors:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Actuators
    analyzers:
      base:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Base
        contains: 'base_driver'

#  safety:
#    type: diagnostic_aggregator/GenericAnalyzer
#    path: Safety
#    contains: 'safety'
